resources:
- name: trivial-app
  type: git
  source:
    uri: https://github.com/totherme/trivial
    branch: master

jobs:
- name: test-trivial-app
  plan:
  - get: trivial-app
    trigger: true
  - task: go-test
    config:
      inputs:
      - name: trivial-app
        path: go/src/github.com/totherme/trivial
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: golang}
      run:
        path: /bin/bash
        args:
        - -c
        - |
          export GOPATH=$PWD/go
          cd $GOPATH/src/github.com/totherme/trivial
          go test ./...
- name: cf-push-trivial-app
  plan:
  - get: trivial-app
    trigger: true
    passed: ["test-trivial-app"]
  - task: cf-push
    config:
      inputs:
      - name: trivial-app
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: governmentpaas/cf-cli}
      params:
        CF_USERNAME: ((cf-username))
        CF_PASSWORD: ((cf-password))
      run:
        dir: trivial-app
        path: sh
        args:
        - -c
        - |
          cf login -u "$CF_USERNAME" -p "$CF_PASSWORD" -a https://api.sys.salinas.cf-app.com --skip-ssl-validation \
          -o testing -s testing
          cf push
