resources:
- name: trivial-app
  type: git
  source:
    uri: https://github.com/totherme/trivial
    branch: master

jobs:
- name: test-trivial-app
  plan:
  - get: trivial-app
    trigger: true
  - task: go-test
    config:
      inputs:
      - name: trivial-app
        path: go/src/github.com/totherme/trivial
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: golang}
      run:
        path: /bin/bash
        args:
        - -c
        - |
          export GOPATH=$PWD/go
          cd $GOPATH/src/github.com/totherme/trivial
          go test ./...
